name: Selenium tests

on:
  workflow_run:
    workflows: ["Deploy libCellML website"]
    types:
      - completed

jobs:
  Run-Python-Selenium-Tests:
    env:
      DISPLAY: :87
    runs-on: ubuntu-22.04
    steps:
      - uses: ouzi-dev/commit-status-updater@v2
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          echo ${{ github.repository }}
      - name: Install selenium
        run: |
          which pip3
          pip3 install selenium webdriver-manager
      - name: Run Xvfb
        run: |
          Xvfb $DISPLAY &
      - name: Setup selenium with Chrome
        run: |
          python3 .github/selenium/install_driver.py
      - name: Run tests
        run: |
          python3 --version
          python3 tests/selenium/run_all_tests.py 
      - uses: ouzi-dev/commit-status-updater@v2
        if: always()
        with:
          status: "${{ job.status }}"
